<?php

print "<!doctype html>\n";
print "<html lang=\"en\">\n";
print "\n";
print "<head>\n";
print "  <!-- To implement bootstrap in a page, type b4-$ -->\n";
print "  <title>RateMyScholar</title>\n";
print "  <!-- Icon for the browser tab -->\n";
print "  <link rel=\"icon\" type=\"image/png\" href=\"../resources/placeholder_logo.png\" sizes=\"16x16\">\n";
print "  <!-- Required meta tags -->\n";
print "  <meta charset=\"utf-8\">\n";
print "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
print "  <!-- Bootstrap CSS -->\n";
print "  <link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
print "  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n";
print "    integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n";
print "  <!-- Custom CSS, use ../CSS/name.css to refer to CSS files from the folder -->\n";
print "  <link rel=\"stylesheet\" type=\"text/css\" href=\"../CSS/login.css\">\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "  <!-- Navigation bar -->\n";
print "  <header>\n";
print "    <nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\n";
print "      <a class=\"navbar-brand\" href=\"index.html\">Rate My Scholar</a>\n";
print "      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\n";
print "        aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
print "        <span class=\"navbar-toggler-icon\"></span>\n";
print "      </button>\n";
print "      <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n";
print "        <ul class=\"navbar-nav\">\n";
print "          <li class=\"nav-item\">\n";
print "            <a class=\"nav-link\" href=\"index.html\">Home<span class=\"sr-only\">(current)</span></a>\n";
print "          </li>\n";
print "          <li class=\"nav-item\">\n";
print "            <a class=\"nav-link\" href=\"register.html\">Register</a>\n";
print "          </li>\n";
print "          <li class=\"nav-item active\">\n";
print "            <a class=\"nav-link\" href=\"#\">Login</a>\n";
print "          </li>\n";
print "        </ul>\n";
print "      </div>\n";
print "    </nav>\n";
print "  </header>\n";
print "  <!-- Log in component -->\n";
print "  <div style=\"padding-top: 5%;\" class=\"container-fluid\">\n";
print "    <h1 class=\"display-4 d-flex justify-content-center\" style=\"color:white; \">Login</h1>\n";
print "    <div class=\"login-form\">\n";
print "      <form action=\"/examples/actions/confirmation.php\" method=\"post\">\n";
print "        <!-- <h2 class=\"text-center\">Log in</h2>        -->\n";
print "        <div class=\"form-group\">\n";
print "          <input type=\"text\" class=\"form-control\" placeholder=\"Username\" required=\"required\">\n";
print "        </div>\n";
print "        <div class=\"form-group\">\n";
print "          <input type=\"password\" class=\"form-control\" placeholder=\"Password\" required=\"required\">\n";
print "        </div>\n";
print "        <div class=\"form-group\">\n";
print "          <button type=\"submit\" class=\"btn btn-primary btn-block\">Log in</button>\n";
print "        </div>\n";
print "        <div class=\"clearfix\">\n";
print "          <label class=\"float-left form-check-label\"><input type=\"checkbox\"> Remember me</label>\n";
print "          <!-- Do I make a forgot password page for this? Probably will in the future\n";
print "                  for now, it is not operational. -->\n";
print "          <a href=\"#\" class=\"float-right\">Forgot Password?</a>\n";
print "        </div>\n";
print "      </form>\n";
print "      <p class=\"text-center\"><a href=\"register.html\">Create an Account</a></p>\n";
print "    </div>\n";
print "  </div>\n";
print "</body>";

?>
