<?php

print "<!doctype html>\n";
print "<html lang=\"en\">\n";
print "\n";
print "<head>\n";
print "  <!-- To implement bootstrap in a page, type b4-$ -->\n";
print "  <title>RateMyScholar</title>\n";
print "  <!-- Icon for the browser tab -->\n";
print "  <link rel=\"icon\" type=\"image/png\" href=\"../resources/placeholder_logo.png\" sizes=\"16x16\">\n";
print "  <!-- Required meta tags -->\n";
print "  <meta charset=\"utf-8\">\n";
print "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
print "\n";
print "  <!-- Bootstrap CSS -->\n";
print "  <link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
print "  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n";
print "    integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n";
print "  <!-- Custom CSS, use ../CSS/name.css to refer to CSS files from the folder -->\n";
print "  <link rel=\"stylesheet\" type=\"text/css\" href=\"../CSS/register.css\">\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "  <!-- Navigation bar -->\n";
print "  <header>\n";
print "    <nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\"> <a class=\"navbar-brand\" href=\"index.html\">Rate\n";
print "        My Scholar</a>\n";
print "      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\n";
print "        aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
print "        <span class=\"navbar-toggler-icon\"></span>\n";
print "      </button>\n";
print "      <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n";
print "        <ul class=\"navbar-nav\">\n";
print "          <li class=\"nav-item\">\n";
print "            <a class=\"nav-link\" href=\"index.html\">Home<span class=\"sr-only\">(current)</span></a>\n";
print "          </li>\n";
print "          <li class=\"nav-item\">\n";
print "            <a class=\"nav-link\" href=\"register.html\">Register</a>\n";
print "          </li>\n";
print "          <li class=\"nav-item\">\n";
print "            <a class=\"nav-link\" href=\"login.html\">Login</a>\n";
print "          </li>\n";
print "        </ul>\n";
print "      </div>\n";
print "    </nav>\n";
print "  </header>\n";
print "  <div style=\"padding-top: 5%;\" class=\"container\">\n";
print "    <!-- Input form component -->\n";
print "    <h1 class=\"display-4 d-flex justify-content-center\" style=\"color: white;\">Rating: John Doe</h1>\n";
print "    <div class=\"row justify-content-center\">\n";
print "      <div class=\"col-md-8\">\n";
print "        <div class=\"card\">\n";
print "          <div class=\"card-header\">Fill out the boxes to complete your review.</div>\n";
print "          <div class=\"card-body\">\n";
print "            <form>\n";
print "              <div class=\"form-group\">\n";
print "                <label for=\"exampleFormControlInput1\">Email address</label>\n";
print "                <input type=\"email\" class=\"form-control\" id=\"exampleFormControlInput1\" placeholder=\"name@example.com\">\n";
print "              </div>\n";
print "              <div class=\"form-group\">\n";
print "                <label for=\"exampleFormControlSelect1\">Star Rating for this scholar</label>\n";
print "                <select class=\"form-control\" id=\"exampleFormControlSelect1\">\n";
print "                  <option>1</option>\n";
print "                  <option>2</option>\n";
print "                  <option>3</option>\n";
print "                  <option>4</option>\n";
print "                  <option>5</option>\n";
print "                </select>\n";
print "              </div>\n";
print "              <div class=\"form-group\">\n";
print "                <label for=\"exampleFormControlTextarea1\">Comments on this scholar</label>\n";
print "                <textarea class=\"form-control\" id=\"exampleFormControlTextarea1\" rows=\"3\">
?>