<?php

print "<!doctype html>\n";
print "<html lang=\"en\">\n";
print "\n";
print "<head>\n";
print "    <!-- To implement bootstrap in a page, type b4-$ -->\n";
print "    <title>RateMyScholar</title>\n";
print "    <!-- Icon for the browser tab -->\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"../resources/placeholder_logo.png\" sizes=\"16x16\">\n";
print "    <!-- Required meta tags -->\n";
print "    <meta charset=\"utf-8\">\n";
print "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
print "\n";
print "    <!-- Bootstrap CSS -->\n";
print "    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n";
print "        integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n";
print "    <!-- Custom CSS, use ../CSS/name.css to refer to CSS files from the folder -->\n";
print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"../CSS/register.css\">\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "    <!-- Navigation bar -->\n";
print "    <header>\n";
print "        <nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\n";
print "            <a class=\"navbar-brand\" href=\"index.html\">Rate My Scholar</a>\n";
print "            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\n";
print "                aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
print "                <span class=\"navbar-toggler-icon\"></span>\n";
print "            </button>\n";
print "            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n";
print "                <ul class=\"navbar-nav\">\n";
print "                    <li class=\"nav-item\">\n";
print "                        <a class=\"nav-link\" href=\"index.html\">Home<span class=\"sr-only\">(current)</span></a>\n";
print "                    </li>\n";
print "                    <li class=\"nav-item active\">\n";
print "                        <a class=\"nav-link\" href=\"#\">Register</a>\n";
print "                    </li>\n";
print "                    <li class=\"nav-item\">\n";
print "                        <a class=\"nav-link\" href=\"login.html\">Login</a>\n";
print "                    </li>\n";
print "                </ul>\n";
print "            </div>\n";
print "        </nav>\n";
print "    </header>\n";
print "    <main style=\"padding-top: 5%;\" class=\"my-form\">\n";
print "        <div class=\"container-fluid\">\n";
print "        <!-- Title component -->\n";
print "        <h1 class=\"display-4 d-flex justify-content-center\"  style=\"color:white;\">Register</h1>\n";
print "        <!-- Register component -->\n";
print "        <div class=\"row justify-content-center\">\n";
print "            <div class=\"col-md-8\">\n";
print "                <div class=\"card\">\n";
print "                    <div class=\"card-header\">Please fill out the boxes to register.</div>\n";
print "                    <div class=\"card-body\">\n";
print "                        <form name=\"my-form\" onsubmit=\"return validform()\" action=\"success.php\" method=\"\">\n";
print "                            <div class=\"form-group row\">\n";
print "                                <label for=\"full_name\" class=\"col-md-4 col-form-label text-md-right\">Full\n";
print "                                    Name</label>\n";
print "                                <div class=\"col-md-6\">\n";
print "                                    <input type=\"text\" id=\"full_name\" class=\"form-control\" name=\"full-name\">\n";
print "                                </div>\n";
print "                            </div>\n";
print "\n";
print "                            <div class=\"form-group row\">\n";
print "                                <label for=\"email_address\" class=\"col-md-4 col-form-label text-md-right\">E-Mail\n";
print "                                    Address</label>\n";
print "                                <div class=\"col-md-6\">\n";
print "                                    <input type=\"text\" id=\"email_address\" class=\"form-control\" name=\"email-address\">\n";
print "                                </div>\n";
print "                            </div>\n";
print "\n";
print "                            <div class=\"form-group row\">\n";
print "                                <label for=\"user_name\" class=\"col-md-4 col-form-label text-md-right\">User\n";
print "                                    Name</label>\n";
print "                                <div class=\"col-md-6\">\n";
print "                                    <input type=\"text\" id=\"user_name\" class=\"form-control\" name=\"username\">\n";
print "                                </div>\n";
print "                            </div>\n";
print "\n";
print "                            <div class=\"form-group row\">\n";
print "                                <label for=\"phone_number\" class=\"col-md-4 col-form-label text-md-right\">Phone\n";
print "                                    Number</label>\n";
print "                                <div class=\"col-md-6\">\n";
print "                                    <input type=\"text\" id=\"phone_number\" class=\"form-control\">\n";
print "                                </div>\n";
print "                            </div>\n";
print "\n";
print "                            <div class=\"form-group row\">\n";
print "                                <label for=\"present_address\"\n";
print "                                    class=\"col-md-4 col-form-label text-md-right\">Address</label>\n";
print "                                <div class=\"col-md-6\">\n";
print "                                    <input type=\"text\" id=\"present_address\" class=\"form-control\">\n";
print "                                </div>\n";
print "                            </div>\n";
print "\n";
print "                            <div class=\"col-md-6 offset-md-4\">\n";
print "                                <button type=\"submit\" class=\"btn btn-primary\">\n";
print "                                    Register\n";
print "                                </button>\n";
print "                            </div>\n";
print "                        </form>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "        </div>\n";
print "        </div>\n";
print "    </main>\n";
print "    \n";
print "</body>\n";
print "\n";
print "</html>";

?>
